config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'pages/home'

  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show]
  resources :events
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :events do
    resources :registrations, only: [:create]
  end
  resources :photos, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_and_belongs_to_many :categories
  validates :name, :starts_at, :ends_at, presence: true
  validates :description, presence: true, length: {maximum: 500}
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user
  has_many :photos, dependent: :destroy

=begin  validate :end_date_after_start_date?

  def end_date_after_start_date?
    if :ends_at < :starts_at
      errors.add :ends_at, "Must be after start date"
    end
  end
=end
def available?
  guests.count < capacity
end

def bargain?
    price < 30
end

def self.order_by_price
    order(:price)
end



end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end
  
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :guest_count, numericality: { less_than_or_equal_to: 3,  only_integer: true }
  before_save :set_total_price

  def set_total_price
    self.price = event.price * guest_count
  end

 def event_available?
   return if event.available?
 end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registered_at_events, through: :registrations, source: :event

 def has_profile?
   profile.present? && !profile.id.nil?
 end

 def full_name
   profile.full_name
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
  @categories = @event.categories
  @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      create_images
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
    @photos = @event.photos
  else
    redirect_to root_path, notice: "You don't have permission."
  end
  end

  def update
    if @event.update(event_params)
      create_images
      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private

  def set_event
        @event = Event.find(params[:id])
      end

  def event_params
      params.require(:event).permit(:name, :description, :location, :price,
      :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :category_ids, :photos)
  end

  def image_params
  params[:images] ? params.require(:images) : []
  end

  def create_images
    image_params.each do |image|
     @event.photos.create(image: image)
   end

  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!
  def create
    @registration = current_user.registrations.create(registration_params)
    if @registration.event_available?
      @registration.save
      redirect_to @registration.event, notice: "Thank you for registering!"
    else
      redirect_to @registration.event, notice: "Sorry, there're no more available tickets for the chosen event."
  end
end

  private

  def registration_params
    params.require(:registration).permit(:price, :guest_count, :status, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, placeholder: "Name of your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "Enter your event's location", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Ticket price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :capacity, placeholder: "eg.6", class: "form-control" %>
    </div>
  </div>

  <label>More about your event</label>

  <div class="form-group">
    <%= f.check_box :includes_food %> Includes food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Includes drinks
  </div>


  <div class="form-group">
    <label>Starts at</label>
  <%= f.datetime_select :starts_at %>
  </div>

  <div class="form-group">
    <label>Ends at</label>
  <%= f.datetime_select :ends_at %>
  </div>

  <label>Photos</label>
    <div id="photos">
      <%= render 'photos/list' %>
    </div>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>


  <label>Publish this event?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit your event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <% if current_user != @event.user %>
    <div class="panel panel-primary">
      <div class="panel-heading">Register for this event</div>

      <div class="panel-body">
        <%= render 'registrations/form' %>
      </div>
    </div>
  <% end %>

  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Address: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Price <%= @event.price %></p>
    <p><%= @event.capacity %> <%= @event.capacity > 1 ? "Guests" : "Guest" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>What's included</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks" %></li>

    </ul>
    <h4>Categories</h4>
<% @categories.each do |category| %>
  <span class="label label-success"><%= category.name %></span>
<% end %>

    <h4>Photos</h4>
    <% @photos.each do |photo| %>
      <%= image_tag photo.image.list_view %>
    <% end %>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", photo_path( photo.id ),
        class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
<% end %>
<% end %>

app/views/profiles/_errors.html.erb
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
<ul>
  <%= render 'errors' %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>